apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- gateway.yaml
- httproute.yaml
images:
- name: gcr.io/dwk-gke-482214/log-reader
  newName: gcr.io/dwk-gke-482214/log-reader
  newTag: 8404648a97d7d6c12f6a027f667c52001683dfb4
- name: gcr.io/dwk-gke-482214/log-writer
  newName: gcr.io/dwk-gke-482214/log-writer
  newTag: 8404648a97d7d6c12f6a027f667c52001683dfb4
