apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- ../../base
images:
- name: PROJECT/TODO_APP
  newName: gcr.io/dwk-gke-482214/todo-app
  newTag: 0e5bbc80d3d137001fd8a32ac3ff047557927018
