apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: DISCORD_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secret
                  key: DISCORD_CHANNEL_ID
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secret
                  key: DISCORD_BOT_TOKEN

