apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- ../../base
patches:
- path: configmap-patch.yaml
- path: deployment-patch.yaml
images:
- name: PROJECT/BROADCASTER
  newName: gcr.io/dwk-gke-482214/broadcaster
  newTag: 0e5bbc80d3d137001fd8a32ac3ff047557927018
