apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
patches:
- path: configmap-patch.yaml
images:
- name: PROJECT/BROADCASTER
  newName: gcr.io/dwk-gke-482214/broadcaster
  newTag: 8404648a97d7d6c12f6a027f667c52001683dfb4
