apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- postgres.yaml
- deployment.yaml
- service.yaml
images:
- name: gcr.io/dwk-gke-482214/pingpong
  newName: gcr.io/dwk-gke-482214/pingpong
  newTag: 8404648a97d7d6c12f6a027f667c52001683dfb4
