apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- ../../base
- backup-cronjob.yaml
patches:
- path: configmap-patch.yaml
images:
- name: PROJECT/TODO_BACKEND
  newName: gcr.io/dwk-gke-482214/todo-backend
  newTag: 173c0e2e02be32e1e6b9964f10d859b6b4c51e35
- name: PROJECT/TODO_BACKUP
  newName: gcr.io/dwk-gke-482214/todo-backup
  newTag: 173c0e2e02be32e1e6b9964f10d859b6b4c51e35
- name: PROJECT/TODO_CRONJOB
  newName: gcr.io/dwk-gke-482214/todo-cronjob
  newTag: 173c0e2e02be32e1e6b9964f10d859b6b4c51e35
