apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- ../../base
- backup-cronjob.yaml
patches:
- path: configmap-patch.yaml
images:
- name: PROJECT/TODO_BACKEND
  newName: gcr.io/dwk-gke-482214/todo-backend
  newTag: aa3f65337d9d67e590d8492d063b48ec34cb1d8a
- name: PROJECT/TODO_BACKUP
  newName: gcr.io/dwk-gke-482214/todo-backup
  newTag: aa3f65337d9d67e590d8492d063b48ec34cb1d8a
- name: PROJECT/TODO_CRONJOB
  newName: gcr.io/dwk-gke-482214/todo-cronjob
  newTag: aa3f65337d9d67e590d8492d063b48ec34cb1d8a
